using Perlax.Modules.Production.Infrastructure.Parsing;
using var ficha = File.OpenRead(@"G:\github\Perlax\backend\src\Host\Perlax.Web\wwwroot\uploads\OTS\existente\viernes\20260813205210_1_ficha_f7858.pdf");
using var op = File.OpenRead(@"G:\github\Perlax\backend\src\Host\Perlax.Web\wwwroot\uploads\OTS\existente\viernes\20260813205210_2_op_o7858.pdf");
var p = ExpertisLegacyPdfParser.Parse(ficha, op);
Console.WriteLine("OP=" + p.OpNumber);
Console.WriteLine("Cliente=" + p.ClientName);
Console.WriteLine("Producto=" + p.ProductName);
Console.WriteLine("Ref=" + p.ReferenceName);
Console.WriteLine("OC=" + p.PurchaseOrderNumber);
Console.WriteLine("Ejec=" + p.EjecutivoCuenta);
Console.WriteLine("Linea=" + p.LineaPT);
Console.WriteLine("Qty=" + p.QuantityToProduce);
Console.WriteLine("Open=" + p.OpeningDate.ToString("yyyy-MM-dd"));
Console.WriteLine("Disp=" + (p.AgreedDeliveryDate?.ToString("yyyy-MM-dd") ?? "-"));
Console.WriteLine("Troquel=" + p.CodigoTroquel);
Console.WriteLine("Medidas=" + p.Alto + "x" + p.Ancho + "x" + p.Largo + " F=" + p.Fuelle);
Console.WriteLine("T1=" + p.Terminado1 + " T2=" + p.Terminado2);
Console.WriteLine("CMYK=" + p.TintaC + "/" + p.TintaM + "/" + p.TintaY + "/" + p.TintaK);
Console.WriteLine("Notes=" + p.MaterialNotes);
Console.WriteLine("Processes=" + p.FabricationProcessesJson);
Console.WriteLine("Warnings=" + string.Join(" | ", p.Warnings));