// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Perlax.Modules.Production.Infrastructure.Persistence;

#nullable disable

namespace Perlax.Modules.Production.Infrastructure.Migrations
{
    [DbContext(typeof(ProductionDbContext))]
    [Migration("20260413163106_AddDesignTrackingFields")]
    partial class AddDesignTrackingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("production")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Perlax.Modules.Production.Domain.Entities.OrderPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjuntosJson")
                        .HasColumnType("text");

                    b.Property<decimal>("Alto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AltoPliego")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Ancho")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AnchoPliego")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Cabida")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoTroquel")
                        .HasColumnType("text");

                    b.Property<bool>("CondicionCertificado")
                        .HasColumnType("boolean");

                    b.Property<bool>("CondicionFactura")
                        .HasColumnType("boolean");

                    b.Property<bool>("CondicionOrdenCompra")
                        .HasColumnType("boolean");

                    b.Property<bool>("CondicionRemision")
                        .HasColumnType("boolean");

                    b.Property<string>("DireccionFibra")
                        .HasColumnType("text");

                    b.Property<string>("DireccionFlauta")
                        .HasColumnType("text");

                    b.Property<string>("Disenador")
                        .HasColumnType("text");

                    b.Property<string>("EstadoAprobacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoArtes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoBoceto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoFicha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoFotomecanica")
                        .HasColumnType("text");

                    b.Property<string>("EstadoMuestra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstadoPlancha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Estampado")
                        .HasColumnType("boolean");

                    b.Property<string>("FabricationProcessesJson")
                        .HasColumnType("text");

                    b.Property<decimal>("Largo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ManijaLargo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ManijaRef")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ManijaTipo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PieImprenta")
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SustratoInf")
                        .HasColumnType("text");

                    b.Property<string>("SustratoMed")
                        .HasColumnType("text");

                    b.Property<string>("SustratoSup")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Terminado1")
                        .HasColumnType("text");

                    b.Property<string>("Terminado2")
                        .HasColumnType("text");

                    b.Property<bool>("TintaC")
                        .HasColumnType("boolean");

                    b.Property<bool>("TintaK")
                        .HasColumnType("boolean");

                    b.Property<bool>("TintaM")
                        .HasColumnType("boolean");

                    b.Property<bool>("TintaY")
                        .HasColumnType("boolean");

                    b.Property<string>("TintasEspeciales")
                        .HasColumnType("text");

                    b.Property<string>("TipoFlauta")
                        .HasColumnType("text");

                    b.Property<bool>("TroquelNuevo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("OrderParts", "production");
                });

            modelBuilder.Entity("Perlax.Modules.Production.Domain.Entities.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Asignacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EjecutivoCuenta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LineaPT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroPartes")
                        .HasColumnType("integer");

                    b.Property<string>("OTNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductionOrders", "production");
                });

            modelBuilder.Entity("Perlax.Modules.Production.Domain.Entities.OrderPart", b =>
                {
                    b.HasOne("Perlax.Modules.Production.Domain.Entities.ProductionOrder", "Order")
                        .WithMany("Parts")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Perlax.Modules.Production.Domain.Entities.ProductionOrder", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
