// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Perlax.Modules.Almacen.Infrastructure.Persistence;

#nullable disable

namespace Perlax.Modules.Almacen.Infrastructure.Migrations
{
    [DbContext(typeof(AlmacenDbContext))]
    partial class AlmacenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("almacen")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenOrdenCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreadoPorNombre")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaPago")
                        .HasColumnType("text");

                    b.Property<string>("NitProveedor")
                        .HasColumnType("text");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroOrdenCompra")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProveedorCatalogoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelefonoProveedor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NumeroOrdenCompra")
                        .IsUnique();

                    b.ToTable("OrdenesCompra", "almacen");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenOrdenCompraLinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrdenCompraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PedidoProveedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisicionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("PedidoProveedorId")
                        .IsUnique();

                    b.ToTable("OrdenCompraLineas", "almacen");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProcesadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcesadoPorNombre")
                        .HasColumnType("text");

                    b.Property<Guid>("RequisicionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisicionId")
                        .IsUnique();

                    b.ToTable("Pedidos", "almacen");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenPedidoProveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaPago")
                        .HasColumnType("text");

                    b.Property<string>("Nit")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroOrdenCompra")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrdenCompraId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Pagado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ProveedorCatalogoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Recibido")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrdenCompraId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoProveedores", "almacen");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostoEstandar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TipoRequisicionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnidadSugerida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Productos", "almacen");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenProveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("ResponsableIva")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("TelefonoMovil")
                        .HasColumnType("text");

                    b.Property<string>("TelefonoTrabajo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proveedores", "almacen");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenRecepcionLinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CalidadEsperada")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CantidadPedidaEnMomento")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("CantidadRecibida")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("CodigoUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FacturaEntregada")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaLlegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoCalidadNo")
                        .HasColumnType("text");

                    b.Property<string>("MotivoCantidadParcial")
                        .HasColumnType("text");

                    b.Property<string>("MotivoFacturaNo")
                        .HasColumnType("text");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NuevaFechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PedidoCompleto")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PedidoProveedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegistradoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegistradoPorNombre")
                        .HasColumnType("text");

                    b.Property<Guid>("RequisicionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisicionId");

                    b.ToTable("RecepcionLineas", "almacen");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenRequisicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnioCodigo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("CatalogoOpId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreadoPorNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRequerida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.Property<string>("OrdenProduccionNumero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SecuenciaCodigo")
                        .HasColumnType("integer");

                    b.Property<string>("TipoRequisicionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("AnioCodigo", "SecuenciaCodigo")
                        .IsUnique();

                    b.ToTable("Requisiciones", "almacen");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenOrdenCompraLinea", b =>
                {
                    b.HasOne("Perlax.Modules.Almacen.Domain.Entities.AlmacenOrdenCompra", "OrdenCompra")
                        .WithMany("Lineas")
                        .HasForeignKey("OrdenCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCompra");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenPedido", b =>
                {
                    b.HasOne("Perlax.Modules.Almacen.Domain.Entities.AlmacenRequisicion", "Requisicion")
                        .WithOne("Pedido")
                        .HasForeignKey("Perlax.Modules.Almacen.Domain.Entities.AlmacenPedido", "RequisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisicion");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenPedidoProveedor", b =>
                {
                    b.HasOne("Perlax.Modules.Almacen.Domain.Entities.AlmacenOrdenCompra", "OrdenCompra")
                        .WithMany()
                        .HasForeignKey("OrdenCompraId");

                    b.HasOne("Perlax.Modules.Almacen.Domain.Entities.AlmacenPedido", "Pedido")
                        .WithMany("Proveedores")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenCompra");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenRecepcionLinea", b =>
                {
                    b.HasOne("Perlax.Modules.Almacen.Domain.Entities.AlmacenRequisicion", "Requisicion")
                        .WithMany("Recepciones")
                        .HasForeignKey("RequisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisicion");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenOrdenCompra", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenPedido", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Perlax.Modules.Almacen.Domain.Entities.AlmacenRequisicion", b =>
                {
                    b.Navigation("Pedido");

                    b.Navigation("Recepciones");
                });
#pragma warning restore 612, 618
        }
    }
}
